#!/bin/bash

FILE=$1
BASE=$(basename $FILE)
shift

mkdir -p tmp

FLAGS=`grep 'FLAGS:' $FILE | sed 's/.*FLAGS: *//' | tr '\n' ' '`

NOTE=""
if [ "$FLAGS" != "" ]
then
  NOTE=" (with $FLAGS)"
fi

echo "== Compiling$NOTE =="

EXEC=$(basename $BASE .hs)

hbmcc $FILE $FLAGS $@ > tmp/$BASE && (cd tmp; ghc --make $BASE -O2 || exit

echo "== Running =="

time ./$EXEC)
