#!/bin/bash

LIMIT=$1
shift
FILE=$1
BASE=$(basename $FILE)
shift

mkdir -p tmp

FLAGS=`grep 'FLAGS:' $FILE | sed 's/.*FLAGS: *//' | tr '\n' ' '`

NOTE=""
if [ "$FLAGS" != "" ]
then
  NOTE=" (with $FLAGS)"
fi

hbmcc $FILE $FLAGS $@ > tmp/$BASE && (cd tmp; ghc --make $BASE -O2

/usr/bin/time -f '%U' timeout $LIMIT ./$(basename $BASE .hs))

