#!/bin/bash

FILE=$1
BASE=$(basename $FILE)
shift

mkdir -p tmp

FLAGS=`grep 'FLAGS:' $FILE | sed 's/.*FLAGS: *//' | tr '\n' ' '`

NOTE=""
if [ "$FLAGS" != "" ]
then
  NOTE=" (with $FLAGS)"
fi

echo "== Compiling$NOTE =="

EXEC=$(basename $(basename $BASE .smt2) .hs)
TMPHS=${EXEC}.hs

hbmcc $FILE $FLAGS $@ > tmp/$TMPHS && (cd tmp; ghc --make $TMPHS -O2 || exit

echo "== Running =="

time ./$EXEC)
