#!/bin/bash

FILE=$1
BASE=$(basename $FILE)
shift

mkdir -p tmp

FLAGS=`grep 'FLAGS:' $FILE | sed 's/.*FLAGS: *//' | tr '\n' ' '`

NOTE=""
if [ "$FLAGS" != "" ]
then
  NOTE=" (with $FLAGS)"
fi

echo "== Compiling$NOTE =="

hbmcc $FILE $FLAGS $@ > tmp/$BASE && (cd tmp; ghc --make $BASE -O2

echo "== Running =="

time ./$(basename $BASE .hs))
