resolver: lts-10.3
packages:
- .

extra-deps:
- minisat-0.1.2
- structural-induction-0.3
- genifunctors-0.4
- twee-lib-2.1.5
- spoon-0.3.1
- git: git://github.com/tip-org/tools.git
  commit: a1f32b0b5e74ba279e6c5f617229a044a4fb0117
  subdirs:
    - tip-types/
    - tip-lib/
